siteTitle = "Shiruco log"
siteDescr = "I'm Front-End Developer."
siteAuthor = "Shiruco"

siteTwitterUrl = "https://twitter.com/shiruco621"
siteGithubUrl = "https://github.com/shiruco"
siteEmailUrl = "shiruco621@gmail.com"

googleAnalyticsId = ""

linkPrefix = "/gatsby-starter-lumen"