siteTitle = "Shiruco log"
siteDescr = "I'm Front-end Developer love interactive contents."
siteAuthor = "Shiruco"

siteTwitterUrl = "https://twitter.com/shiruco621"
siteGithubUrl = "https://github.com/shiruco"
siteEmailUrl = "shiruco621@gmail.com"

googleAnalyticsId = "UA-90940990-1"

linkPrefix = "/shiruco-log"